name: admin_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Fonts/Montserrat-Regular.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/utils
  filename: appImages.dart
  field_prefix:
